name: todo-app

services:
  postgres:
    image: postgres:17-alpine
    container_name: todo-resource
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    volumes:
      - todo-data:/var/lib/postgresql/data
      - ./_entrypoint:/docker-entrypoint-initdb.d:ro
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - todo-net

  app:
    image: monote/preflight-backend
    container_name: todo-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${APP_PORT:-3000}
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - postgres
    post_start:
      - command: npm run migration:run
    networks:
      - todo-net

volumes:
  todo-data:
    driver: local

networks:
  todo-net:
    driver: bridge
